# Copyright (C) 2016 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/Gionee/p5mini/setup-makefiles.sh

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/Gionee/p5mini/bin,system/bin)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/Gionee/p5mini/etc,system/etc)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/Gionee/p5mini/lib,system/lib)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/Gionee/p5mini/lib64,system/lib64)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/Gionee/p5mini/usr,system/usr)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/Gionee/p5mini/plugin,system/plugin)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/Gionee/p5mini/vendor/pittpatt,system/vendor/pittpatt)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/Gionee/p5mini/vendor/media,system/vendor/media)

PRODUCT_COPY_FILES += $(call find-copy-subdir-files,*,vendor/Gionee/p5mini/vendor/lib,system/vendor/lib)
